# Chapter 6: Reading and Writing Data

In [1]:
import polars as pl
pl.__version__  # The book is built with Polars version 1.20.0

'2.0.0'

## Format Overview

## Reading CSV Files

In [ ]:
! cat data/penguins.csv

In [2]:
penguins = pl.read_csv("data/penguins.csv")
penguins

shape: (344, 9)
┌───────┬───────────┬───────────┬────────────────┬───┬───────────────┬─────────────┬────────┬──────┐
│ rowid ┆ species   ┆ island    ┆ bill_length_mm ┆ … ┆ flipper_lengt ┆ body_mass_g ┆ sex    ┆ year │
│ ---   ┆ ---       ┆ ---       ┆ ---            ┆   ┆ h_mm          ┆ ---         ┆ ---    ┆ ---  │
│ i64   ┆ str       ┆ str       ┆ str            ┆   ┆ ---           ┆ str         ┆ str    ┆ i64  │
│       ┆           ┆           ┆                ┆   ┆ str           ┆             ┆        ┆      │
╞═══════╪═══════════╪═══════════╪════════════════╪═══╪═══════════════╪═════════════╪════════╪══════╡
│ 1     ┆ Adelie    ┆ Torgersen ┆ 39.1           ┆ … ┆ 181           ┆ 3750        ┆ male   ┆ 2007 │
│ 2     ┆ Adelie    ┆ Torgersen ┆ 39.5           ┆ … ┆ 186           ┆ 3800        ┆ female ┆ 2007 │
│ 3     ┆ Adelie    ┆ Torgersen ┆ 40.3           ┆ … ┆ 195           ┆ 3250        ┆ female ┆ 2007 │
│ 4     ┆ Adelie    ┆ Torgersen ┆ NA             ┆ … ┆ NA            ┆ NA          ┆ NA     ┆ 2007 │
│ 5     ┆ Adelie    ┆ Torgersen ┆ 36.7           ┆ … ┆ 193           ┆ 3450        ┆ female ┆ 2007 │
│ …     ┆ …         ┆ …         ┆ …              ┆ … ┆ …             ┆ …           ┆ …      ┆ …    │
│ 340   ┆ Chinstrap ┆ Dream     ┆ 55.8           ┆ … ┆ 207           ┆ 4000        ┆ male   ┆ 2009 │
│ 341   ┆ Chinstrap ┆ Dream     ┆ 43.5           ┆ … ┆ 202           ┆ 3400        ┆ female ┆ 2009 │
│ 342   ┆ Chinstrap ┆ Dream     ┆ 49.6           ┆ … ┆ 193           ┆ 3775        ┆ male   ┆ 2009 │
│ 343   ┆ Chinstrap ┆ Dream     ┆ 50.8           ┆ … ┆ 210           ┆ 4100        ┆ male   ┆ 2009 │
│ 344   ┆ Chinstrap ┆ Dream     ┆ 50.2           ┆ … ┆ 198           ┆ 3775        ┆ female ┆ 2009 │
└───────┴───────────┴───────────┴────────────────┴───┴───────────────┴─────────────┴────────┴──────┘

## Parsing Missing Values Correctly

In [3]:
penguins = pl.read_csv("data/penguins.csv", null_values="NA")
penguins

shape: (344, 9)
┌───────┬───────────┬───────────┬────────────────┬───┬───────────────┬─────────────┬────────┬──────┐
│ rowid ┆ species   ┆ island    ┆ bill_length_mm ┆ … ┆ flipper_lengt ┆ body_mass_g ┆ sex    ┆ year │
│ ---   ┆ ---       ┆ ---       ┆ ---            ┆   ┆ h_mm          ┆ ---         ┆ ---    ┆ ---  │
│ i64   ┆ str       ┆ str       ┆ f64            ┆   ┆ ---           ┆ i64         ┆ str    ┆ i64  │
│       ┆           ┆           ┆                ┆   ┆ i64           ┆             ┆        ┆      │
╞═══════╪═══════════╪═══════════╪════════════════╪═══╪═══════════════╪═════════════╪════════╪══════╡
│ 1     ┆ Adelie    ┆ Torgersen ┆ 39.1           ┆ … ┆ 181           ┆ 3750        ┆ male   ┆ 2007 │
│ 2     ┆ Adelie    ┆ Torgersen ┆ 39.5           ┆ … ┆ 186           ┆ 3800        ┆ female ┆ 2007 │
│ 3     ┆ Adelie    ┆ Torgersen ┆ 40.3           ┆ … ┆ 195           ┆ 3250        ┆ female ┆ 2007 │
│ 4     ┆ Adelie    ┆ Torgersen ┆ null           ┆ … ┆ null          ┆ null        ┆ null   ┆ 2007 │
│ 5     ┆ Adelie    ┆ Torgersen ┆ 36.7           ┆ … ┆ 193           ┆ 3450        ┆ female ┆ 2007 │
│ …     ┆ …         ┆ …         ┆ …              ┆ … ┆ …             ┆ …           ┆ …      ┆ …    │
│ 340   ┆ Chinstrap ┆ Dream     ┆ 55.8           ┆ … ┆ 207           ┆ 4000        ┆ male   ┆ 2009 │
│ 341   ┆ Chinstrap ┆ Dream     ┆ 43.5           ┆ … ┆ 202           ┆ 3400        ┆ female ┆ 2009 │
│ 342   ┆ Chinstrap ┆ Dream     ┆ 49.6           ┆ … ┆ 193           ┆ 3775        ┆ male   ┆ 2009 │
│ 343   ┆ Chinstrap ┆ Dream     ┆ 50.8           ┆ … ┆ 210           ┆ 4100        ┆ male   ┆ 2009 │
│ 344   ┆ Chinstrap ┆ Dream     ┆ 50.2           ┆ … ┆ 198           ┆ 3775        ┆ female ┆ 2009 │
└───────┴───────────┴───────────┴────────────────┴───┴───────────────┴─────────────┴────────┴──────┘

In [4]:
penguins.null_count().transpose(  
    include_header=True, column_names=["null_count"]
)

shape: (9, 2)
┌───────────────────┬────────────┐
│ column            ┆ null_count │
│ ---               ┆ ---        │
│ str               ┆ u32        │
╞═══════════════════╪════════════╡
│ rowid             ┆ 0          │
│ species           ┆ 0          │
│ island            ┆ 0          │
│ bill_length_mm    ┆ 2          │
│ bill_depth_mm     ┆ 2          │
│ flipper_length_mm ┆ 2          │
│ body_mass_g       ┆ 2          │
│ sex               ┆ 11         │
│ year              ┆ 0          │
└───────────────────┴────────────┘

## Reading Files with Encodings Other Than UTF-8

In [ ]:
# This raises a ComputeError:
# pl.read_csv("data/directors.csv")

In [4]:
pl.read_csv("data/directors.csv", encoding="EUC-CN")

shape: (4, 3)
┌───────────┬──────┬──────────┐
│ name      ┆ born ┆ country  │
│ ---       ┆ ---  ┆ ---      │
│ str       ┆ i64  ┆ str      │
╞═══════════╪══════╪══════════╡
│ 考侯      ┆ 1930 ┆ 泣塑     │
│ Verhoeven ┆ 1938 ┆ オランダ │
│ 弟宏      ┆ 1942 ┆ 泣塑     │
│ Tarantino ┆ 1963 ┆ 势柜     │
└───────────┴──────┴──────────┘

In [6]:
import chardet


def detect_encoding(filename: str) -> str:
    """Return the most probable character encoding for a file."""

    with open(filename, "rb") as f:
        raw_data = f.read()
        result = chardet.detect(raw_data)
        return result["encoding"]


detect_encoding("data/directors.csv")

ModuleNotFoundError: No module named 'chardet'

In [5]:
pl.read_csv("data/directors.csv", encoding="EUC-JP")

shape: (4, 3)
┌───────────┬──────┬──────────┐
│ name      ┆ born ┆ country  │
│ ---       ┆ ---  ┆ ---      │
│ str       ┆ i64  ┆ str      │
╞═══════════╪══════╪══════════╡
│ 深作      ┆ 1930 ┆ 日本     │
│ Verhoeven ┆ 1938 ┆ オランダ │
│ 宮崎      ┆ 1942 ┆ 日本     │
│ Tarantino ┆ 1963 ┆ 米国     │
└───────────┴──────┴──────────┘

## Reading Excel Spreadsheets

In [6]:
songs = pl.read_excel("data/top2000-2023.xlsx")  
songs

shape: (2_000, 4)
┌─────────┬─────────────────────────┬────────────────┬──────┐
│ positie ┆ titel                   ┆ artiest        ┆ jaar │
│ ---     ┆ ---                     ┆ ---            ┆ ---  │
│ i64     ┆ str                     ┆ str            ┆ i64  │
╞═════════╪═════════════════════════╪════════════════╪══════╡
│ 1       ┆ Bohemian Rhapsody       ┆ Queen          ┆ 1975 │
│ 2       ┆ Roller Coaster          ┆ Danny Vera     ┆ 2019 │
│ 3       ┆ Hotel California        ┆ Eagles         ┆ 1977 │
│ 4       ┆ Piano Man               ┆ Billy Joel     ┆ 1974 │
│ 5       ┆ Fix You                 ┆ Coldplay       ┆ 2005 │
│ …       ┆ …                       ┆ …              ┆ …    │
│ 1996    ┆ Charlie Brown           ┆ Coldplay       ┆ 2011 │
│ 1997    ┆ Beast Of Burden         ┆ Bette Midler   ┆ 1984 │
│ 1998    ┆ It Was A Very Good Year ┆ Frank Sinatra  ┆ 1968 │
│ 1999    ┆ Hou Van Mij             ┆ 3JS            ┆ 2008 │
│ 2000    ┆ Drivers License         ┆ Olivia Rodrigo ┆ 2021 │
└─────────┴─────────────────────────┴────────────────┴──────┘

## Working with Multiple Files

In [7]:
pl.read_csv("data/stock/nvda/201?.csv")

shape: (2_516, 8)
┌────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┬──────────┐
│ symbol ┆ date       ┆ open      ┆ high      ┆ low       ┆ close     ┆ adj close ┆ volume   │
│ ---    ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str    ┆ str        ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ i64      │
╞════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╪══════════╡
│ NVDA   ┆ 2010-01-04 ┆ 4.6275    ┆ 4.655     ┆ 4.5275    ┆ 4.6225    ┆ 4.240429  ┆ 80020400 │
│ NVDA   ┆ 2010-01-05 ┆ 4.605     ┆ 4.74      ┆ 4.605     ┆ 4.69      ┆ 4.30235   ┆ 72864800 │
│ NVDA   ┆ 2010-01-06 ┆ 4.6875    ┆ 4.73      ┆ 4.6425    ┆ 4.72      ┆ 4.32987   ┆ 64916800 │
│ NVDA   ┆ 2010-01-07 ┆ 4.695     ┆ 4.715     ┆ 4.5925    ┆ 4.6275    ┆ 4.245015  ┆ 54779200 │
│ NVDA   ┆ 2010-01-08 ┆ 4.59      ┆ 4.67      ┆ 4.5625    ┆ 4.6375    ┆ 4.254189  ┆ 47816800 │
│ …      ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         ┆ …        │
│ NVDA   ┆ 2019-12-24 ┆ 59.549999 ┆ 59.827499 ┆ 59.205002 ┆ 59.654999 ┆ 59.422798 ┆ 13886400 │
│ NVDA   ┆ 2019-12-26 ┆ 59.689999 ┆ 60.080002 ┆ 59.5      ┆ 59.797501 ┆ 59.564739 ┆ 18285200 │
│ NVDA   ┆ 2019-12-27 ┆ 59.950001 ┆ 60.084999 ┆ 58.952499 ┆ 59.217499 ┆ 58.987    ┆ 25464400 │
│ NVDA   ┆ 2019-12-30 ┆ 58.997501 ┆ 59.049999 ┆ 57.764999 ┆ 58.080002 ┆ 57.853928 ┆ 25805600 │
│ NVDA   ┆ 2019-12-31 ┆ 57.724998 ┆ 58.919998 ┆ 57.532501 ┆ 58.825001 ┆ 58.596027 ┆ 23100400 │
└────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┴──────────┘

In [8]:
all_stocks = pl.read_csv("data/stock/**/*.csv")
all_stocks

shape: (18_476, 8)
┌────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬──────────┐
│ symbol ┆ date       ┆ open       ┆ high       ┆ low        ┆ close      ┆ adj close  ┆ volume   │
│ ---    ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---      │
│ str    ┆ str        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ i64      │
╞════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪══════════╡
│ ASML   ┆ 1999-01-04 ┆ 11.765625  ┆ 12.28125   ┆ 11.765625  ┆ 12.140625  ┆ 7.522523   ┆ 1801867  │
│ ASML   ┆ 1999-01-05 ┆ 11.859375  ┆ 14.25      ┆ 11.71875   ┆ 13.96875   ┆ 8.655257   ┆ 8241600  │
│ ASML   ┆ 1999-01-06 ┆ 14.25      ┆ 17.601563  ┆ 14.203125  ┆ 16.875     ┆ 10.456018  ┆ 16400267 │
│ ASML   ┆ 1999-01-07 ┆ 14.742188  ┆ 17.8125    ┆ 14.53125   ┆ 16.851563  ┆ 10.441495  ┆ 17722133 │
│ ASML   ┆ 1999-01-08 ┆ 16.078125  ┆ 16.289063  ┆ 15.023438  ┆ 15.796875  ┆ 9.787995   ┆ 10696000 │
│ …      ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …        │
│ TSM    ┆ 2023-06-26 ┆ 102.019997 ┆ 103.040001 ┆ 100.089996 ┆ 100.110001 ┆ 99.125954  ┆ 8560000  │
│ TSM    ┆ 2023-06-27 ┆ 101.150002 ┆ 102.790001 ┆ 100.019997 ┆ 102.080002 ┆ 101.076591 ┆ 9732000  │
│ TSM    ┆ 2023-06-28 ┆ 100.5      ┆ 101.879997 ┆ 100.220001 ┆ 100.919998 ┆ 99.927986  ┆ 8160900  │
│ TSM    ┆ 2023-06-29 ┆ 101.339996 ┆ 101.519997 ┆ 100.019997 ┆ 100.639999 ┆ 99.650742  ┆ 7383900  │
│ TSM    ┆ 2023-06-30 ┆ 101.400002 ┆ 101.889999 ┆ 100.410004 ┆ 100.919998 ┆ 99.927986  ┆ 11701700 │
└────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴──────────┘

In [9]:
import calendar

filenames = [
    f"data/stock/asml/{year}.csv"
    for year in range(1999, 2024)
    if calendar.isleap(year)
]

filenames

['data/stock/asml/2000.csv',
 'data/stock/asml/2004.csv',
 'data/stock/asml/2008.csv',
 'data/stock/asml/2012.csv',
 'data/stock/asml/2016.csv',
 'data/stock/asml/2020.csv']

In [10]:
pl.concat(pl.read_csv(f) for f in filenames)

shape: (1_512, 8)
┌────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬─────────┐
│ symbol ┆ date       ┆ open       ┆ high       ┆ low        ┆ close      ┆ adj close  ┆ volume  │
│ ---    ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---     │
│ str    ┆ str        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ i64     │
╞════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪═════════╡
│ ASML   ┆ 2000-01-03 ┆ 43.875     ┆ 43.875     ┆ 41.90625   ┆ 43.640625  ┆ 27.040424  ┆ 1121600 │
│ ASML   ┆ 2000-01-04 ┆ 41.953125  ┆ 42.5625    ┆ 40.59375   ┆ 40.734375  ┆ 25.239666  ┆ 968800  │
│ ASML   ┆ 2000-01-05 ┆ 39.28125   ┆ 39.703125  ┆ 37.757813  ┆ 39.609375  ┆ 24.542597  ┆ 1458133 │
│ ASML   ┆ 2000-01-06 ┆ 36.75      ┆ 37.59375   ┆ 35.226563  ┆ 37.171875  ┆ 23.032274  ┆ 3517867 │
│ ASML   ┆ 2000-01-07 ┆ 36.867188  ┆ 38.0625    ┆ 36.65625   ┆ 38.015625  ┆ 23.555077  ┆ 1631200 │
│ …      ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …       │
│ ASML   ┆ 2020-12-24 ┆ 478.950012 ┆ 484.600006 ┆ 477.079987 ┆ 483.089996 ┆ 468.836365 ┆ 271900  │
│ ASML   ┆ 2020-12-28 ┆ 487.140015 ┆ 488.720001 ┆ 478.429993 ┆ 480.23999  ┆ 466.070496 ┆ 449300  │
│ ASML   ┆ 2020-12-29 ┆ 489.450012 ┆ 489.450012 ┆ 482.51001  ┆ 484.01001  ┆ 469.729218 ┆ 377200  │
│ ASML   ┆ 2020-12-30 ┆ 488.130005 ┆ 492.660004 ┆ 488.0      ┆ 489.910004 ┆ 475.455231 ┆ 381900  │
│ ASML   ┆ 2020-12-31 ┆ 490.0      ┆ 490.519989 ┆ 483.450012 ┆ 487.720001 ┆ 473.329803 ┆ 312700  │
└────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴─────────┘

## Reading Parquet

In [11]:
%%time
trips = pl.read_parquet("data/taxi/yellow_tripdata_*.parquet")

CPU times: total: 20.3 s
Wall time: 1.11 s

## Reading JSON and NDJSON

### JSON

In [ ]:
! cat data/pokedex.json

In [12]:
pokedex = pl.read_json("data/pokedex.json")
pokedex

shape: (1, 1)
┌─────────────────────────────────┐
│ pokemon                         │
│ ---                             │
│ list[struct[17]]                │
╞═════════════════════════════════╡
│ [{1,"001","Bulbasaur","http://… │
└─────────────────────────────────┘

In [13]:
(
    pokedex.explode("pokemon")
    .unnest("pokemon")
    .select("id", "name", "type", "height", "weight")
)

shape: (151, 5)
┌─────┬────────────┬──────────────────────┬────────┬──────────┐
│ id  ┆ name       ┆ type                 ┆ height ┆ weight   │
│ --- ┆ ---        ┆ ---                  ┆ ---    ┆ ---      │
│ i64 ┆ str        ┆ list[str]            ┆ str    ┆ str      │
╞═════╪════════════╪══════════════════════╪════════╪══════════╡
│ 1   ┆ Bulbasaur  ┆ ["Grass", "Poison"]  ┆ 0.71 m ┆ 6.9 kg   │
│ 2   ┆ Ivysaur    ┆ ["Grass", "Poison"]  ┆ 0.99 m ┆ 13.0 kg  │
│ 3   ┆ Venusaur   ┆ ["Grass", "Poison"]  ┆ 2.01 m ┆ 100.0 kg │
│ 4   ┆ Charmander ┆ ["Fire"]             ┆ 0.61 m ┆ 8.5 kg   │
│ 5   ┆ Charmeleon ┆ ["Fire"]             ┆ 1.09 m ┆ 19.0 kg  │
│ …   ┆ …          ┆ …                    ┆ …      ┆ …        │
│ 147 ┆ Dratini    ┆ ["Dragon"]           ┆ 1.80 m ┆ 3.3 kg   │
│ 148 ┆ Dragonair  ┆ ["Dragon"]           ┆ 3.99 m ┆ 16.5 kg  │
│ 149 ┆ Dragonite  ┆ ["Dragon", "Flying"] ┆ 2.21 m ┆ 210.0 kg │
│ 150 ┆ Mewtwo     ┆ ["Psychic"]          ┆ 2.01 m ┆ 122.0 kg │
│ 151 ┆ Mew        ┆ ["Psychic"]          ┆ 0.41 m ┆ 4.0 kg   │
└─────┴────────────┴──────────────────────┴────────┴──────────┘

### NDJSON

In [ ]:
! cat data/wikimedia.ndjson

In [15]:
from json import loads
from pprint import pprint

with open("data/wikimedia.ndjson") as f:
    pprint(loads(f.readline()))

{'$schema': '/mediawiki/recentchange/1.0.0',
 'bot': False,
 'comment': '/* League champions, runners-up and play-off finalists */',
 'id': 1659529639,
 'length': {'new': 91166, 'old': 91108},
 'meta': {'domain': 'en.wikipedia.org',
          'dt': '2023-07-29T07:51:39Z',
          'id': '0416300b-980c-45bb-b0a2-c9d7a9e2b7eb',
          'offset': 4820784717,
          'partition': 0,
          'request_id': 'ea0541fb-4e72-4fc3-82f0-6c26651b2043',
          'stream': 'mediawiki.recentchange',
          'topic': 'eqiad.mediawiki.recentchange',
          'uri': 'https://en.wikipedia.org/wiki/EFL_Championship'},
 'minor': False,
 'namespace': 0,
 'notify_url': 'https://en.wikipedia.org/w/index.php?diff=1167689309&oldid=1166824248',
 'parsedcomment': '<span dir="auto"><span class="autocomment"><a '
                  'href="/wiki/EFL_Championship#League_champions,_runners-up_and_play-off_finalists" '
                  'title="EFL Championship">→\u200eLeague champions, '
                  'runners-up and play-off finalists</a></span></span>',
 'revision': {'new': 1167689309, 'old': 1166824248},
 'server_name': 'en.wikipedia.org',
 'server_script_path': '/w',
 'server_url': 'https://en.wikipedia.org',
 'timestamp': 1690617099,
 'title': 'EFL Championship',
 'title_url': 'https://en.wikipedia.org/wiki/EFL_Championship',
 'type': 'edit',
 'user': '87.12.215.232',
 'wiki': 'enwiki'}

In [16]:
wikimedia = pl.read_ndjson("data/wikimedia.ndjson")
wikimedia

shape: (100, 20)
┌─────────────┬────────────┬────────────┬──────┬───┬────────────┬────────────┬────────┬────────────┐
│ $schema     ┆ meta       ┆ id         ┆ type ┆ … ┆ server_nam ┆ server_scr ┆ wiki   ┆ parsedcomm │
│ ---         ┆ ---        ┆ ---        ┆ ---  ┆   ┆ e          ┆ ipt_path   ┆ ---    ┆ ent        │
│ str         ┆ struct[9]  ┆ i64        ┆ str  ┆   ┆ ---        ┆ ---        ┆ str    ┆ ---        │
│             ┆            ┆            ┆      ┆   ┆ str        ┆ str        ┆        ┆ str        │
╞═════════════╪════════════╪════════════╪══════╪═══╪════════════╪════════════╪════════╪════════════╡
│ /mediawiki/ ┆ {"https:// ┆ 1659529639 ┆ edit ┆ … ┆ en.wikiped ┆ /w         ┆ enwiki ┆ <span dir= │
│ recentchang ┆ en.wikiped ┆            ┆      ┆   ┆ ia.org     ┆            ┆        ┆ "auto"><sp │
│ e/1.0.0     ┆ ia.org/wik ┆            ┆      ┆   ┆            ┆            ┆        ┆ an         │
│             ┆ …          ┆            ┆      ┆   ┆            ┆            ┆        ┆ class="…   │
│ /mediawiki/ ┆ {"https:// ┆ 1659529640 ┆ edit ┆ … ┆ en.wikiped ┆ /w         ┆ enwiki ┆            │
│ recentchang ┆ en.wikiped ┆            ┆      ┆   ┆ ia.org     ┆            ┆        ┆            │
│ e/1.0.0     ┆ ia.org/wik ┆            ┆      ┆   ┆            ┆            ┆        ┆            │
│             ┆ …          ┆            ┆      ┆   ┆            ┆            ┆        ┆            │
│ /mediawiki/ ┆ {"https:// ┆ 1659529642 ┆ edit ┆ … ┆ en.wikiped ┆ /w         ┆ enwiki ┆ <span dir= │
│ recentchang ┆ en.wikiped ┆            ┆      ┆   ┆ ia.org     ┆            ┆        ┆ "auto"><sp │
│ e/1.0.0     ┆ ia.org/wik ┆            ┆      ┆   ┆            ┆            ┆        ┆ an         │
│             ┆ …          ┆            ┆      ┆   ┆            ┆            ┆        ┆ class="…   │
│ /mediawiki/ ┆ {"https:// ┆ 1659529643 ┆ edit ┆ … ┆ en.wikiped ┆ /w         ┆ enwiki ┆ Nominated  │
│ recentchang ┆ en.wikiped ┆            ┆      ┆   ┆ ia.org     ┆            ┆        ┆ for        │
│ e/1.0.0     ┆ ia.org/wik ┆            ┆      ┆   ┆            ┆            ┆        ┆ deletion;  │
│             ┆ …          ┆            ┆      ┆   ┆            ┆            ┆        ┆ see <a…    │
│ /mediawiki/ ┆ {"https:// ┆ 1659529653 ┆ edit ┆ … ┆ en.wikiped ┆ /w         ┆ enwiki ┆ Rescuing 1 │
│ recentchang ┆ en.wikiped ┆            ┆      ┆   ┆ ia.org     ┆            ┆        ┆ sources    │
│ e/1.0.0     ┆ ia.org/wik ┆            ┆      ┆   ┆            ┆            ┆        ┆ and        │
│             ┆ …          ┆            ┆      ┆   ┆            ┆            ┆        ┆ tagging…   │
│ …           ┆ …          ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …      ┆ …          │
│ /mediawiki/ ┆ {"https:// ┆ 1659529961 ┆ edit ┆ … ┆ en.wikiped ┆ /w         ┆ enwiki ┆ <span dir= │
│ recentchang ┆ en.wikiped ┆            ┆      ┆   ┆ ia.org     ┆            ┆        ┆ "auto"><sp │
│ e/1.0.0     ┆ ia.org/wik ┆            ┆      ┆   ┆            ┆            ┆        ┆ an         │
│             ┆ …          ┆            ┆      ┆   ┆            ┆            ┆        ┆ class="…   │
│ /mediawiki/ ┆ {"https:// ┆ 1659529963 ┆ edit ┆ … ┆ en.wikiped ┆ /w         ┆ enwiki ┆ Ce         │
│ recentchang ┆ en.wikiped ┆            ┆      ┆   ┆ ia.org     ┆            ┆        ┆            │
│ e/1.0.0     ┆ ia.org/wik ┆            ┆      ┆   ┆            ┆            ┆        ┆            │
│             ┆ …          ┆            ┆      ┆   ┆            ┆            ┆        ┆            │
│ /mediawiki/ ┆ {"https:// ┆ 1659529964 ┆ edit ┆ … ┆ en.wikiped ┆ /w         ┆ enwiki ┆            │
│ recentchang ┆ en.wikiped ┆            ┆      ┆   ┆ ia.org     ┆            ┆        ┆            │
│ e/1.0.0     ┆ ia.org/wik ┆            ┆      ┆   ┆            ┆            ┆        ┆            │
│             ┆ …          ┆            ┆      ┆   ┆            ┆            ┆        ┆            │
│ /mediawiki/ ┆ {"https:// ┆ 1659529965 ┆ edit ┆ … ┆ en.wikiped ┆ /w         ┆ enwiki ┆            │
│ recentchang ┆ en.wikiped ┆            ┆      ┆   ┆ ia.org     ┆            ┆        ┆            │
│ e/1.0.0     ┆ ia.org/wik ┆            ┆      ┆   ┆            ┆            ┆        ┆            │
│             ┆ …          ┆            ┆      ┆   ┆            ┆            ┆        ┆            │
│ /mediawiki/ ┆ {"https:// ┆ 1659529966 ┆ edit ┆ … ┆ en.wikiped ┆ /w         ┆ enwiki ┆ <span dir= │
│ recentchang ┆ en.wikiped ┆            ┆      ┆   ┆ ia.org     ┆            ┆        ┆ "auto"><sp │
│ e/1.0.0     ┆ ia.org/wik ┆            ┆      ┆   ┆            ┆            ┆        ┆ an         │
│             ┆ …          ┆            ┆      ┆   ┆            ┆            ┆        ┆ class="…   │
└─────────────┴────────────┴────────────┴──────┴───┴────────────┴────────────┴────────┴────────────┘

In [17]:
(
    wikimedia.rename({"id": "edit_id"})
    .unnest("meta")
    .select("timestamp", "title", "user", "comment")
)

shape: (100, 4)
┌────────────┬────────────────────────────┬────────────────────────────┬───────────────────────────┐
│ timestamp  ┆ title                      ┆ user                       ┆ comment                   │
│ ---        ┆ ---                        ┆ ---                        ┆ ---                       │
│ i64        ┆ str                        ┆ str                        ┆ str                       │
╞════════════╪════════════════════════════╪════════════════════════════╪═══════════════════════════╡
│ 1690617099 ┆ EFL Championship           ┆ 87.12.215.232              ┆ /* League champions,      │
│            ┆                            ┆                            ┆ runners-u…                │
│ 1690617102 ┆ Lim Sang-choon             ┆ Preferwiki                 ┆                           │
│ 1690617104 ┆ Higher                     ┆ Ss112                      ┆ /* Albums */ add          │
│ 1690617104 ┆ International Poker Rules  ┆ Piotrus                    ┆ Nominated for deletion;   │
│            ┆                            ┆                            ┆ see [[…                   │
│ 1690617105 ┆ Abdul Hamid Khan Bhashani  ┆ InternetArchiveBot         ┆ Rescuing 1 sources and    │
│            ┆                            ┆                            ┆ tagging…                  │
│ …          ┆ …                          ┆ …                          ┆ …                         │
│ 1690617238 ┆ Havering Residents         ┆ MRSC                       ┆ /* 2018 election */ +map  │
│            ┆ Association                ┆                            ┆                           │
│ 1690617235 ┆ Olha Kharlan               ┆ 2603:7000:2101:AA00:2C88:E ┆ Ce                        │
│            ┆                            ┆ F86:…                      ┆                           │
│ 1690617238 ┆ Mukim Kota Batu            ┆ Pangalau                   ┆                           │
│ 1690617239 ┆ User:IDK1213safasx/sandbox ┆ 94.101.29.27               ┆                           │
│ 1690617234 ┆ List of bus routes in      ┆ Pedroperezhumberto         ┆ /* Non-TfL bus routes in  │
│            ┆ London                     ┆                            ┆ Great…                    │
└────────────┴────────────────────────────┴────────────────────────────┴───────────────────────────┘

## Other File Formats

In [14]:
import pandas as pd

url = "https://en.wikipedia.org/wiki/List_of_Latin_abbreviations"
pl.from_pandas(pd.read_html(url, storage_options={"User-Agent": "Mozilla/5.0"})[0])

shape: (58, 4)
┌──────────────┬───────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ Abbreviation ┆ Latin         ┆ Translation                     ┆ Usage and notes                 │
│ ---          ┆ ---           ┆ ---                             ┆ ---                             │
│ str          ┆ str           ┆ str                             ┆ str                             │
╞══════════════╪═══════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ AD           ┆ anno Domini   ┆ "in the year of the Lord"       ┆ Used to label or number years … │
│ a.i.         ┆ ad interim    ┆ "temporarily"                   ┆ Used in business organizationa… │
│ a.m.         ┆ ante meridiem ┆ "before midday"[1]              ┆ Used on the twelve-hour clock … │
│ ca. c.       ┆ circa         ┆ "around", "about", "approximat… ┆ Used with dates to indicate "a… │
│ Cap.         ┆ capitulus     ┆ "chapter"                       ┆ Used before a chapter number o… │
│ …            ┆ …             ┆ …                               ┆ …                               │
│ SOS          ┆ si opus sit   ┆ "if there is need", "if occasi… ┆ A prescription indication that… │
│ sic          ┆ sic           ┆ "thus"                          ┆ Used when quoting text that co… │
│ stat.        ┆ statim        ┆ "immediately"                   ┆ Often used in medical contexts… │
│ viz.         ┆ videlicet     ┆ "namely", "to wit", "precisely… ┆ In contradistinction to "i.e."… │
│ vs. v.       ┆ versus        ┆ "against"                       ┆ Sometimes is not abbreviated. … │
└──────────────┴───────────────┴─────────────────────────────────┴─────────────────────────────────┘

## Querying Databases

In [20]:
import duckdb

db = duckdb.connect('./data/sakila.db')

In [24]:
db.sql("""show tables""")

┌────────────────────────┐
│          name          │
│        varchar         │
├────────────────────────┤
│ actor                  │
│ address                │
│ category               │
│ city                   │
│ country                │
│ customer               │
│ customer_list          │
│ film                   │
│ film_actor             │
│ film_category          │
│ film_list              │
│ film_text              │
│ inventory              │
│ language               │
│ payment                │
│ rental                 │
│ sales_by_film_category │
│ sales_by_store         │
│ staff                  │
│ staff_list             │
│ store                  │
└────────────────────────┘
         21 rows

In [23]:
db.sql(
    """
    SELECT
        f.film_id,
        f.title,
        c.name AS category,
        f.rating,
        f.length / 60.0 AS length
    FROM
        film AS f,
        film_category AS fc,
        category AS c
    WHERE
        fc.film_id = f.film_id
        AND fc.category_id = c.category_id
    LIMIT 10
    """
).pl()

shape: (10, 5)
┌─────────┬──────────────────┬─────────────┬────────┬──────────┐
│ film_id ┆ title            ┆ category    ┆ rating ┆ length   │
│ ---     ┆ ---              ┆ ---         ┆ ---    ┆ ---      │
│ i64     ┆ str              ┆ str         ┆ str    ┆ f64      │
╞═════════╪══════════════════╪═════════════╪════════╪══════════╡
│ 1       ┆ ACADEMY DINOSAUR ┆ Documentary ┆ PG     ┆ 1.433333 │
│ 2       ┆ ACE GOLDFINGER   ┆ Horror      ┆ G      ┆ 0.8      │
│ 3       ┆ ADAPTATION HOLES ┆ Documentary ┆ NC-17  ┆ 0.833333 │
│ 4       ┆ AFFAIR PREJUDICE ┆ Horror      ┆ G      ┆ 1.95     │
│ 5       ┆ AFRICAN EGG      ┆ Family      ┆ G      ┆ 2.166667 │
│ 6       ┆ AGENT TRUMAN     ┆ Foreign     ┆ PG     ┆ 2.816667 │
│ 7       ┆ AIRPLANE SIERRA  ┆ Comedy      ┆ PG-13  ┆ 1.033333 │
│ 8       ┆ AIRPORT POLLOCK  ┆ Horror      ┆ R      ┆ 0.9      │
│ 9       ┆ ALABAMA DEVIL    ┆ Horror      ┆ PG-13  ┆ 1.9      │
│ 10      ┆ ALADDIN CALENDAR ┆ Sports      ┆ NC-17  ┆ 1.05     │
└─────────┴──────────────────┴─────────────┴────────┴──────────┘

In [19]:
pl.read_database_uri(
    query="""
    SELECT
        f.film_id,
        f.title,
        c.name AS category,
        f.rating,
        f.length / 60.0 AS length
    FROM
        film AS f,
        film_category AS fc,
        category AS c
    WHERE
        fc.film_id = f.film_id
        AND fc.category_id = c.category_id
    LIMIT 10
    """,
    uri="sqlite:::data/sakila.db",
)

shape: (10, 5)
┌─────────┬──────────────────┬─────────────┬────────┬──────────┐
│ film_id ┆ title            ┆ category    ┆ rating ┆ length   │
│ ---     ┆ ---              ┆ ---         ┆ ---    ┆ ---      │
│ i64     ┆ str              ┆ str         ┆ str    ┆ f64      │
╞═════════╪══════════════════╪═════════════╪════════╪══════════╡
│ 1       ┆ ACADEMY DINOSAUR ┆ Documentary ┆ PG     ┆ 1.433333 │
│ 2       ┆ ACE GOLDFINGER   ┆ Horror      ┆ G      ┆ 0.8      │
│ 3       ┆ ADAPTATION HOLES ┆ Documentary ┆ NC-17  ┆ 0.833333 │
│ 4       ┆ AFFAIR PREJUDICE ┆ Horror      ┆ G      ┆ 1.95     │
│ 5       ┆ AFRICAN EGG      ┆ Family      ┆ G      ┆ 2.166667 │
│ 6       ┆ AGENT TRUMAN     ┆ Foreign     ┆ PG     ┆ 2.816667 │
│ 7       ┆ AIRPLANE SIERRA  ┆ Comedy      ┆ PG-13  ┆ 1.033333 │
│ 8       ┆ AIRPORT POLLOCK  ┆ Horror      ┆ R      ┆ 0.9      │
│ 9       ┆ ALABAMA DEVIL    ┆ Horror      ┆ PG-13  ┆ 1.9      │
│ 10      ┆ ALADDIN CALENDAR ┆ Sports      ┆ NC-17  ┆ 1.05     │
└─────────┴──────────────────┴─────────────┴────────┴──────────┘

In [25]:
db = "sqlite:::data/sakila.db"
films = pl.read_database_uri("SELECT * FROM film", db)
film_categories = pl.read_database_uri("SELECT * FROM film_category", db)
categories = pl.read_database_uri("SELECT * FROM category", db)

(
    films.join(film_categories, on="film_id", suffix="_fc")
    .join(categories, on="category_id", suffix="_c")
    .select(
        "film_id",
        "title",
        pl.col("name").alias("category"),
        "rating",
        pl.col("length") / 60,
    )
    .limit(10)
)

shape: (10, 5)
┌─────────┬──────────────────┬─────────────┬────────┬──────────┐
│ film_id ┆ title            ┆ category    ┆ rating ┆ length   │
│ ---     ┆ ---              ┆ ---         ┆ ---    ┆ ---      │
│ i64     ┆ str              ┆ str         ┆ str    ┆ f64      │
╞═════════╪══════════════════╪═════════════╪════════╪══════════╡
│ 1       ┆ ACADEMY DINOSAUR ┆ Documentary ┆ PG     ┆ 1.433333 │
│ 2       ┆ ACE GOLDFINGER   ┆ Horror      ┆ G      ┆ 0.8      │
│ 3       ┆ ADAPTATION HOLES ┆ Documentary ┆ NC-17  ┆ 0.833333 │
│ 4       ┆ AFFAIR PREJUDICE ┆ Horror      ┆ G      ┆ 1.95     │
│ 5       ┆ AFRICAN EGG      ┆ Family      ┆ G      ┆ 2.166667 │
│ 6       ┆ AGENT TRUMAN     ┆ Foreign     ┆ PG     ┆ 2.816667 │
│ 7       ┆ AIRPLANE SIERRA  ┆ Comedy      ┆ PG-13  ┆ 1.033333 │
│ 8       ┆ AIRPORT POLLOCK  ┆ Horror      ┆ R      ┆ 0.9      │
│ 9       ┆ ALABAMA DEVIL    ┆ Horror      ┆ PG-13  ┆ 1.9      │
│ 10      ┆ ALADDIN CALENDAR ┆ Sports      ┆ NC-17  ┆ 1.05     │
└─────────┴──────────────────┴─────────────┴────────┴──────────┘

## Writing Data

### CSV Format

In [ ]:
all_stocks.write_csv("data/all_stocks.csv")

### Excel Format

In [ ]:
all_stocks.write_excel("data/all_stocks.xlsx")

### Parquet Format

In [ ]:
all_stocks.write_parquet("data/all_stocks.parquet")

### Other Considerations

## Takeaways