# Chapter 6: Reading and Writing Data

In [1]:
import polars as pl
pl.__version__  # The book is built with Polars version 1.20.0

'2.0.0'

## Format Overview

## Reading CSV Files

In [ ]:
! cat data/penguins.csv

In [6]:
penguins = pl.read_csv("data/penguins.csv")
penguins

shape: (344, 9)
┌───────┬───────────┬───────────┬────────────────┬───┬───────────────┬─────────────┬────────┬──────┐
│ rowid ┆ species   ┆ island    ┆ bill_length_mm ┆ … ┆ flipper_lengt ┆ body_mass_g ┆ sex    ┆ year │
│ ---   ┆ ---       ┆ ---       ┆ ---            ┆   ┆ h_mm          ┆ ---         ┆ ---    ┆ ---  │
│ i64   ┆ str       ┆ str       ┆ str            ┆   ┆ ---           ┆ str         ┆ str    ┆ i64  │
│       ┆           ┆           ┆                ┆   ┆ str           ┆             ┆        ┆      │
╞═══════╪═══════════╪═══════════╪════════════════╪═══╪═══════════════╪═════════════╪════════╪══════╡
│ 1     ┆ Adelie    ┆ Torgersen ┆ 39.1           ┆ … ┆ 181           ┆ 3750        ┆ male   ┆ 2007 │
│ 2     ┆ Adelie    ┆ Torgersen ┆ 39.5           ┆ … ┆ 186           ┆ 3800        ┆ female ┆ 2007 │
│ 3     ┆ Adelie    ┆ Torgersen ┆ 40.3           ┆ … ┆ 195           ┆ 3250        ┆ female ┆ 2007 │
│ 4     ┆ Adelie    ┆ Torgersen ┆ NA             ┆ … ┆ NA            ┆ NA          ┆ NA     ┆ 2007 │
│ 5     ┆ Adelie    ┆ Torgersen ┆ 36.7           ┆ … ┆ 193           ┆ 3450        ┆ female ┆ 2007 │
│ …     ┆ …         ┆ …         ┆ …              ┆ … ┆ …             ┆ …           ┆ …      ┆ …    │
│ 340   ┆ Chinstrap ┆ Dream     ┆ 55.8           ┆ … ┆ 207           ┆ 4000        ┆ male   ┆ 2009 │
│ 341   ┆ Chinstrap ┆ Dream     ┆ 43.5           ┆ … ┆ 202           ┆ 3400        ┆ female ┆ 2009 │
│ 342   ┆ Chinstrap ┆ Dream     ┆ 49.6           ┆ … ┆ 193           ┆ 3775        ┆ male   ┆ 2009 │
│ 343   ┆ Chinstrap ┆ Dream     ┆ 50.8           ┆ … ┆ 210           ┆ 4100        ┆ male   ┆ 2009 │
│ 344   ┆ Chinstrap ┆ Dream     ┆ 50.2           ┆ … ┆ 198           ┆ 3775        ┆ female ┆ 2009 │
└───────┴───────────┴───────────┴────────────────┴───┴───────────────┴─────────────┴────────┴──────┘

## Parsing Missing Values Correctly

In [3]:
penguins = pl.read_csv("data/penguins.csv", null_values="NA")
penguins

shape: (344, 9)
┌───────┬───────────┬───────────┬────────────────┬───┬───────────────┬─────────────┬────────┬──────┐
│ rowid ┆ species   ┆ island    ┆ bill_length_mm ┆ … ┆ flipper_lengt ┆ body_mass_g ┆ sex    ┆ year │
│ ---   ┆ ---       ┆ ---       ┆ ---            ┆   ┆ h_mm          ┆ ---         ┆ ---    ┆ ---  │
│ i64   ┆ str       ┆ str       ┆ f64            ┆   ┆ ---           ┆ i64         ┆ str    ┆ i64  │
│       ┆           ┆           ┆                ┆   ┆ i64           ┆             ┆        ┆      │
╞═══════╪═══════════╪═══════════╪════════════════╪═══╪═══════════════╪═════════════╪════════╪══════╡
│ 1     ┆ Adelie    ┆ Torgersen ┆ 39.1           ┆ … ┆ 181           ┆ 3750        ┆ male   ┆ 2007 │
│ 2     ┆ Adelie    ┆ Torgersen ┆ 39.5           ┆ … ┆ 186           ┆ 3800        ┆ female ┆ 2007 │
│ 3     ┆ Adelie    ┆ Torgersen ┆ 40.3           ┆ … ┆ 195           ┆ 3250        ┆ female ┆ 2007 │
│ 4     ┆ Adelie    ┆ Torgersen ┆ null           ┆ … ┆ null          ┆ null        ┆ null   ┆ 2007 │
│ 5     ┆ Adelie    ┆ Torgersen ┆ 36.7           ┆ … ┆ 193           ┆ 3450        ┆ female ┆ 2007 │
│ …     ┆ …         ┆ …         ┆ …              ┆ … ┆ …             ┆ …           ┆ …      ┆ …    │
│ 340   ┆ Chinstrap ┆ Dream     ┆ 55.8           ┆ … ┆ 207           ┆ 4000        ┆ male   ┆ 2009 │
│ 341   ┆ Chinstrap ┆ Dream     ┆ 43.5           ┆ … ┆ 202           ┆ 3400        ┆ female ┆ 2009 │
│ 342   ┆ Chinstrap ┆ Dream     ┆ 49.6           ┆ … ┆ 193           ┆ 3775        ┆ male   ┆ 2009 │
│ 343   ┆ Chinstrap ┆ Dream     ┆ 50.8           ┆ … ┆ 210           ┆ 4100        ┆ male   ┆ 2009 │
│ 344   ┆ Chinstrap ┆ Dream     ┆ 50.2           ┆ … ┆ 198           ┆ 3775        ┆ female ┆ 2009 │
└───────┴───────────┴───────────┴────────────────┴───┴───────────────┴─────────────┴────────┴──────┘

In [ ]:
penguins.null_count().transpose(  
    include_header=True, column_names=["null_count"]
)

## Reading Files with Encodings Other Than UTF-8

In [ ]:
# This raises a ComputeError:
# pl.read_csv("data/directors.csv")

In [7]:
pl.read_csv("data/directors.csv", encoding="EUC-CN")

shape: (4, 3)
┌───────────┬──────┬──────────┐
│ name      ┆ born ┆ country  │
│ ---       ┆ ---  ┆ ---      │
│ str       ┆ i64  ┆ str      │
╞═══════════╪══════╪══════════╡
│ 考侯      ┆ 1930 ┆ 泣塑     │
│ Verhoeven ┆ 1938 ┆ オランダ │
│ 弟宏      ┆ 1942 ┆ 泣塑     │
│ Tarantino ┆ 1963 ┆ 势柜     │
└───────────┴──────┴──────────┘

In [9]:
import chardet


def detect_encoding(filename: str) -> str:
    """Return the most probable character encoding for a file."""

    with open(filename, "rb") as f:
        raw_data = f.read()
        result = chardet.detect(raw_data)
        return result["encoding"]


detect_encoding("data/directors.csv")

'EUC-JP'

In [10]:
pl.read_csv("data/directors.csv", encoding="EUC-JP")

shape: (4, 3)
┌───────────┬──────┬──────────┐
│ name      ┆ born ┆ country  │
│ ---       ┆ ---  ┆ ---      │
│ str       ┆ i64  ┆ str      │
╞═══════════╪══════╪══════════╡
│ 深作      ┆ 1930 ┆ 日本     │
│ Verhoeven ┆ 1938 ┆ オランダ │
│ 宮崎      ┆ 1942 ┆ 日本     │
│ Tarantino ┆ 1963 ┆ 米国     │
└───────────┴──────┴──────────┘

## Reading Excel Spreadsheets

In [11]:
songs = pl.read_excel("data/top2000-2023.xlsx")  
songs

shape: (2_000, 4)
┌─────────┬─────────────────────────┬────────────────┬──────┐
│ positie ┆ titel                   ┆ artiest        ┆ jaar │
│ ---     ┆ ---                     ┆ ---            ┆ ---  │
│ i64     ┆ str                     ┆ str            ┆ i64  │
╞═════════╪═════════════════════════╪════════════════╪══════╡
│ 1       ┆ Bohemian Rhapsody       ┆ Queen          ┆ 1975 │
│ 2       ┆ Roller Coaster          ┆ Danny Vera     ┆ 2019 │
│ 3       ┆ Hotel California        ┆ Eagles         ┆ 1977 │
│ 4       ┆ Piano Man               ┆ Billy Joel     ┆ 1974 │
│ 5       ┆ Fix You                 ┆ Coldplay       ┆ 2005 │
│ …       ┆ …                       ┆ …              ┆ …    │
│ 1996    ┆ Charlie Brown           ┆ Coldplay       ┆ 2011 │
│ 1997    ┆ Beast Of Burden         ┆ Bette Midler   ┆ 1984 │
│ 1998    ┆ It Was A Very Good Year ┆ Frank Sinatra  ┆ 1968 │
│ 1999    ┆ Hou Van Mij             ┆ 3JS            ┆ 2008 │
│ 2000    ┆ Drivers License         ┆ Olivia Rodrigo ┆ 2021 │
└─────────┴─────────────────────────┴────────────────┴──────┘

## Working with Multiple Files

In [12]:
pl.read_csv("data/stock/nvda/201?.csv")

shape: (2_516, 8)
┌────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┬──────────┐
│ symbol ┆ date       ┆ open      ┆ high      ┆ low       ┆ close     ┆ adj close ┆ volume   │
│ ---    ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str    ┆ str        ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ i64      │
╞════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╪══════════╡
│ NVDA   ┆ 2010-01-04 ┆ 4.6275    ┆ 4.655     ┆ 4.5275    ┆ 4.6225    ┆ 4.240429  ┆ 80020400 │
│ NVDA   ┆ 2010-01-05 ┆ 4.605     ┆ 4.74      ┆ 4.605     ┆ 4.69      ┆ 4.30235   ┆ 72864800 │
│ NVDA   ┆ 2010-01-06 ┆ 4.6875    ┆ 4.73      ┆ 4.6425    ┆ 4.72      ┆ 4.32987   ┆ 64916800 │
│ NVDA   ┆ 2010-01-07 ┆ 4.695     ┆ 4.715     ┆ 4.5925    ┆ 4.6275    ┆ 4.245015  ┆ 54779200 │
│ NVDA   ┆ 2010-01-08 ┆ 4.59      ┆ 4.67      ┆ 4.5625    ┆ 4.6375    ┆ 4.254189  ┆ 47816800 │
│ …      ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         ┆ …        │
│ NVDA   ┆ 2019-12-24 ┆ 59.549999 ┆ 59.827499 ┆ 59.205002 ┆ 59.654999 ┆ 59.422798 ┆ 13886400 │
│ NVDA   ┆ 2019-12-26 ┆ 59.689999 ┆ 60.080002 ┆ 59.5      ┆ 59.797501 ┆ 59.564739 ┆ 18285200 │
│ NVDA   ┆ 2019-12-27 ┆ 59.950001 ┆ 60.084999 ┆ 58.952499 ┆ 59.217499 ┆ 58.987    ┆ 25464400 │
│ NVDA   ┆ 2019-12-30 ┆ 58.997501 ┆ 59.049999 ┆ 57.764999 ┆ 58.080002 ┆ 57.853928 ┆ 25805600 │
│ NVDA   ┆ 2019-12-31 ┆ 57.724998 ┆ 58.919998 ┆ 57.532501 ┆ 58.825001 ┆ 58.596027 ┆ 23100400 │
└────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┴──────────┘

In [13]:
all_stocks = pl.read_csv("data/stock/**/*.csv")
all_stocks

shape: (18_476, 8)
┌────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬──────────┐
│ symbol ┆ date       ┆ open       ┆ high       ┆ low        ┆ close      ┆ adj close  ┆ volume   │
│ ---    ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---      │
│ str    ┆ str        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ i64      │
╞════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪══════════╡
│ ASML   ┆ 1999-01-04 ┆ 11.765625  ┆ 12.28125   ┆ 11.765625  ┆ 12.140625  ┆ 7.522523   ┆ 1801867  │
│ ASML   ┆ 1999-01-05 ┆ 11.859375  ┆ 14.25      ┆ 11.71875   ┆ 13.96875   ┆ 8.655257   ┆ 8241600  │
│ ASML   ┆ 1999-01-06 ┆ 14.25      ┆ 17.601563  ┆ 14.203125  ┆ 16.875     ┆ 10.456018  ┆ 16400267 │
│ ASML   ┆ 1999-01-07 ┆ 14.742188  ┆ 17.8125    ┆ 14.53125   ┆ 16.851563  ┆ 10.441495  ┆ 17722133 │
│ ASML   ┆ 1999-01-08 ┆ 16.078125  ┆ 16.289063  ┆ 15.023438  ┆ 15.796875  ┆ 9.787995   ┆ 10696000 │
│ …      ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …        │
│ TSM    ┆ 2023-06-26 ┆ 102.019997 ┆ 103.040001 ┆ 100.089996 ┆ 100.110001 ┆ 99.125954  ┆ 8560000  │
│ TSM    ┆ 2023-06-27 ┆ 101.150002 ┆ 102.790001 ┆ 100.019997 ┆ 102.080002 ┆ 101.076591 ┆ 9732000  │
│ TSM    ┆ 2023-06-28 ┆ 100.5      ┆ 101.879997 ┆ 100.220001 ┆ 100.919998 ┆ 99.927986  ┆ 8160900  │
│ TSM    ┆ 2023-06-29 ┆ 101.339996 ┆ 101.519997 ┆ 100.019997 ┆ 100.639999 ┆ 99.650742  ┆ 7383900  │
│ TSM    ┆ 2023-06-30 ┆ 101.400002 ┆ 101.889999 ┆ 100.410004 ┆ 100.919998 ┆ 99.927986  ┆ 11701700 │
└────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴──────────┘

In [14]:
import calendar

filenames = [
    f"data/stock/asml/{year}.csv"
    for year in range(1999, 2024)
    if calendar.isleap(year)
]

filenames

['data/stock/asml/2000.csv',
 'data/stock/asml/2004.csv',
 'data/stock/asml/2008.csv',
 'data/stock/asml/2012.csv',
 'data/stock/asml/2016.csv',
 'data/stock/asml/2020.csv']

In [15]:
pl.concat(pl.read_csv(f) for f in filenames)

shape: (1_512, 8)
┌────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬─────────┐
│ symbol ┆ date       ┆ open       ┆ high       ┆ low        ┆ close      ┆ adj close  ┆ volume  │
│ ---    ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---     │
│ str    ┆ str        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ f64        ┆ i64     │
╞════════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╪═════════╡
│ ASML   ┆ 2000-01-03 ┆ 43.875     ┆ 43.875     ┆ 41.90625   ┆ 43.640625  ┆ 27.040424  ┆ 1121600 │
│ ASML   ┆ 2000-01-04 ┆ 41.953125  ┆ 42.5625    ┆ 40.59375   ┆ 40.734375  ┆ 25.239666  ┆ 968800  │
│ ASML   ┆ 2000-01-05 ┆ 39.28125   ┆ 39.703125  ┆ 37.757813  ┆ 39.609375  ┆ 24.542597  ┆ 1458133 │
│ ASML   ┆ 2000-01-06 ┆ 36.75      ┆ 37.59375   ┆ 35.226563  ┆ 37.171875  ┆ 23.032274  ┆ 3517867 │
│ ASML   ┆ 2000-01-07 ┆ 36.867188  ┆ 38.0625    ┆ 36.65625   ┆ 38.015625  ┆ 23.555077  ┆ 1631200 │
│ …      ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …       │
│ ASML   ┆ 2020-12-24 ┆ 478.950012 ┆ 484.600006 ┆ 477.079987 ┆ 483.089996 ┆ 468.836365 ┆ 271900  │
│ ASML   ┆ 2020-12-28 ┆ 487.140015 ┆ 488.720001 ┆ 478.429993 ┆ 480.23999  ┆ 466.070496 ┆ 449300  │
│ ASML   ┆ 2020-12-29 ┆ 489.450012 ┆ 489.450012 ┆ 482.51001  ┆ 484.01001  ┆ 469.729218 ┆ 377200  │
│ ASML   ┆ 2020-12-30 ┆ 488.130005 ┆ 492.660004 ┆ 488.0      ┆ 489.910004 ┆ 475.455231 ┆ 381900  │
│ ASML   ┆ 2020-12-31 ┆ 490.0      ┆ 490.519989 ┆ 483.450012 ┆ 487.720001 ┆ 473.329803 ┆ 312700  │
└────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴─────────┘

## Reading Parquet

In [ ]:
%%time
trips = pl.read_parquet("data/taxi/yellow_tripdata_*.parquet")

## Reading JSON and NDJSON

### JSON

In [ ]:
! cat data/pokedex.json

In [ ]:
pokedex = pl.read_json("data/pokedex.json")
pokedex

In [ ]:
(
    pokedex.explode("pokemon")
    .unnest("pokemon")
    .select("id", "name", "type", "height", "weight")
)

### NDJSON

In [ ]:
! cat data/wikimedia.ndjson

In [ ]:
from json import loads
from pprint import pprint

with open("data/wikimedia.ndjson") as f:
    pprint(loads(f.readline()))

In [ ]:
wikimedia = pl.read_ndjson("data/wikimedia.ndjson")
wikimedia

In [ ]:
(
    wikimedia.rename({"id": "edit_id"})
    .unnest("meta")
    .select("timestamp", "title", "user", "comment")
)

## Other File Formats

In [ ]:
import pandas as pd

url = "https://en.wikipedia.org/wiki/List_of_Latin_abbreviations"
pl.from_pandas(pd.read_html(url, storage_options={"User-Agent": "Mozilla/5.0"})[0])

## Querying Databases

In [ ]:
pl.read_database_uri(
    query="""
    SELECT
        f.film_id,
        f.title,
        c.name AS category,
        f.rating,
        f.length / 60.0 AS length
    FROM
        film AS f,
        film_category AS fc,
        category AS c
    WHERE
        fc.film_id = f.film_id
        AND fc.category_id = c.category_id
    LIMIT 10
    """,
    uri="sqlite:::data/sakila.db",
)

In [ ]:
db = "sqlite:::data/sakila.db"
films = pl.read_database_uri("SELECT * FROM film", db)
film_categories = pl.read_database_uri("SELECT * FROM film_category", db)
categories = pl.read_database_uri("SELECT * FROM category", db)

(
    films.join(film_categories, on="film_id", suffix="_fc")
    .join(categories, on="category_id", suffix="_c")
    .select(
        "film_id",
        "title",
        pl.col("name").alias("category"),
        "rating",
        pl.col("length") / 60,
    )
    .limit(10)
)

## Writing Data

### CSV Format

In [ ]:
all_stocks.write_csv("data/all_stocks.csv")

### Excel Format

In [ ]:
all_stocks.write_excel("data/all_stocks.xlsx")

### Parquet Format

In [ ]:
all_stocks.write_parquet("data/all_stocks.parquet")

### Other Considerations

## Takeaways